#!/usr/bin/env python3
"""Regenerate nix/prusa-slicer/deps-sources.nix from the recipes in deps/+*/.

Every dependency recipe pins a source archive with `URL` and `URL_HASH SHA256=`.
The Nix build cannot download during the build, so the archives are fetched
by Nix ahead of time and dropped into the download directory that CMake's
ExternalProject expects (<download dir>/<package>/<archive basename>).

Run this script after touching anything under deps/ and commit the result.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEPS = ROOT / "deps"
OUT = ROOT / "nix" / "prusa-slicer" / "deps-sources.nix"

# Packages that are never built by the Nix package (see deps.nix), so their
# archives are not fetched either.
SKIP = {"OpenCSG", "sentry"}

URL_RE = re.compile(r'^\s*URL\s+"?([^"\s]+)"?\s*$')
HASH_RE = re.compile(r'^\s*URL_HASH\s+SHA256=([0-9A-Fa-f]{64})\)?\s*$')


def strip_comment(line: str) -> str:
    return line.split("#", 1)[0]


def parse(recipe: Path):
    url = sha = None
    for raw in recipe.read_text().splitlines():
        line = strip_comment(raw)
        m = URL_RE.match(line)
        if m:
            if url is not None:
                sys.exit(f"{recipe}: more than one URL, please update the script")
            url = m.group(1)
            continue
        m = HASH_RE.match(line)
        if m:
            sha = m.group(1).lower()
    return url, sha


def main():
    entries = []
    for pkgdir in sorted(DEPS.glob("+*")):
        name = pkgdir.name[1:]
        recipe = pkgdir / f"{name}.cmake"
        if not recipe.is_file() or name in SKIP:
            continue
        url, sha = parse(recipe)
        if url is None:
            # Recipes without a URL (e.g. libraries copied from the tree) need nothing.
            continue
        if sha is None:
            sys.exit(f"{recipe}: URL without URL_HASH")
        entries.append((name, url, sha))

    lines = [
        "# Generated by nix/update-deps-sources.py from deps/+*/*.cmake. Do not edit by hand.",
        "#",
        "# One entry per dependency built by deps/CMakeLists.txt: the archive URL and the",
        "# SHA256 that the recipe pins. `name` is the ExternalProject name, which is also",
        "# the sub-directory of the download directory that CMake looks in.",
        "[",
    ]
    for name, url, sha in entries:
        lines += [
            "  {",
            f'    name = "{name}";',
            f'    url = "{url}";',
            f'    sha256 = "{sha}";',
            "  }",
        ]
    lines.append("]")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(entries)} sources)")


if __name__ == "__main__":
    main()
