# Generated by nix/update-deps-sources.py from deps/+*/*.cmake. Do not edit by hand.
#
# One entry per dependency built by deps/CMakeLists.txt: the archive URL and the
# SHA256 that the recipe pins. `name` is the ExternalProject name, which is also
# the sub-directory of the download directory that CMake looks in.
[
  {
    name = "Blosc";
    url = "https://github.com/Blosc/c-blosc/archive/refs/tags/v1.21.6.zip";
    sha256 = "1919c97d55023c04aa8771ea8235b63e9da3c22e3d2a68340b33710d19c2a2eb";
  }
  {
    name = "Boost";
    url = "https://github.com/boostorg/boost/releases/download/boost-1.86.0/boost-1.86.0-cmake.zip";
    sha256 = "a66084ec52c9dfa838b3b225a29f29869b2d11e201b3f9e4b989431d95b671c2";
  }
  {
    name = "CGAL";
    url = "https://github.com/CGAL/cgal/archive/refs/tags/v5.6.2.zip";
    sha256 = "29acaeee5a76a95029fac23131bb1c3a4a75df9a0e7e43b465a1f32d0628f45d";
  }
  {
    name = "CLI11";
    url = "https://github.com/CLIUtils/CLI11/archive/refs/tags/v2.5.0.zip";
    sha256 = "887270cae374a0b9e22b39647f9fc4bc742587fb26d6a221da2d2bbcf3109b0b";
  }
  {
    name = "CURL";
    url = "https://github.com/curl/curl/releases/download/curl-8_21_0/curl-8.21.0.zip";
    sha256 = "a99651d2b9ee0bf858c590078b1b0f989c187b07009e88bf94c0ec614be1bc7d";
  }
  {
    name = "Catch2";
    url = "https://github.com/catchorg/Catch2/archive/refs/tags/v3.8.0.zip";
    sha256 = "bffd2c45a84e5a4b0c17e695798e8d2f65931cbaf5c7556d40388d1d8d04eb83";
  }
  {
    name = "Cereal";
    url = "https://github.com/USCiLab/cereal/archive/refs/tags/v1.3.2.zip";
    sha256 = "e72c3fa8fe3d531247773e346e6824a4744cc6472a25cf9b30599cd52146e2ae";
  }
  {
    name = "EXPAT";
    url = "https://github.com/libexpat/libexpat/releases/download/R_2_8_2/expat-2.8.2.tar.gz";
    sha256 = "ef7d1994f533c9e7343d6c19f31064fc8ebbcbcaa144be3812b4f43052a05f4c";
  }
  {
    name = "Eigen";
    url = "https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.zip";
    sha256 = "eba3f3d414d2f8cba2919c78ec6daab08fc71ba2ba4ae502b7e5d4d99fc02cda";
  }
  {
    name = "GLEW";
    url = "https://sourceforge.net/projects/glew/files/glew/2.2.0/glew-2.2.0.zip";
    sha256 = "a9046a913774395a095edcc0b0ac2d81c3aacca61787b39839b941e9be14e0d4";
  }
  {
    name = "GLFW";
    url = "https://github.com/glfw/glfw/releases/download/3.3.9/glfw-3.3.9.zip";
    sha256 = "55261410f8c3a9cc47ce8303468a90f40a653cd8f25fb968b12440624fb26d08";
  }
  {
    name = "GMP";
    url = "https://gmplib.org/download/gmp/gmp-6.2.1.tar.bz2";
    sha256 = "eae9326beb4158c386e39a356818031bd28f3124cf915f8c5b1dc4c7a36b4d7c";
  }
  {
    name = "Imath";
    url = "https://github.com/AcademySoftwareFoundation/Imath/archive/refs/tags/v3.1.12.zip";
    sha256 = "82d8f31c46e73dba92525bea29c4fe077f6a7d3b978d5067a15030413710bf46";
  }
  {
    name = "JPEG";
    url = "https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/3.0.1.zip";
    sha256 = "d6d99e693366bc03897677650e8b2dfa76b5d6c54e2c9e70c03f0af821b0a52f";
  }
  {
    name = "LibAssert";
    url = "https://github.com/jeremy-rifkin/libassert/archive/refs/tags/v2.2.1.zip";
    sha256 = "a4728a2cc6d2672ba29443bbb871c2529a8a812f2d504c92a0b9b9cff1779117";
  }
  {
    name = "LibBGCode";
    url = "https://github.com/prusa3d/libbgcode/archive/d4da9073616d70a43c151e8c1d7fbff879d2e08a.zip";
    sha256 = "73076348e80315d1c2584f883c6b07637cd847c74bca7e9279e42b56a308f948";
  }
  {
    name = "Lua";
    url = "https://www.lua.org/ftp/lua-5.4.8.tar.gz";
    sha256 = "4f18ddae154e793e46eeab727c59ef1c0c0c2b744e7b94219710d76f530629ae";
  }
  {
    name = "MPFR";
    url = "https://www.mpfr.org/mpfr-4.2.1/mpfr-4.2.1.tar.bz2";
    sha256 = "b9df93635b20e4089c29623b19420c4ac848a1b29df1cfd59f26cab0d2666aa0";
  }
  {
    name = "NLopt";
    url = "https://github.com/stevengj/nlopt/archive/v2.5.0.tar.gz";
    sha256 = "c6dd7a5701fff8ad5ebb45a3dc8e757e61d52658de3918e38bab233e7fd3b4ae";
  }
  {
    name = "NanoSVG";
    url = "https://github.com/fltk/nanosvg/archive/abcd277ea45e9098bed752cf9c6875b533c0892f.zip";
    sha256 = "e859938fbaee4b351bd8a8b3d3c7a75b40c36885ce00b73faa1ce0b98aa0ad34";
  }
  {
    name = "OCCT";
    url = "https://github.com/Open-Cascade-SAS/OCCT/archive/refs/tags/V7_6_1.zip";
    sha256 = "b7cf65430d6f099adc9df1749473235de7941120b5b5dd356067d12d0909b1d3";
  }
  {
    name = "OpenEXR";
    url = "https://github.com/AcademySoftwareFoundation/openexr/releases/download/v3.2.10/openexr-3.2.10.tar.gz";
    sha256 = "9a61920ae2056b6f0f44e73e7001fa3fac45f266b65c29401cc9d33dd9d41050";
  }
  {
    name = "OpenSSL";
    url = "https://github.com/openssl/openssl/releases/download/openssl-4.0.1/openssl-4.0.1.tar.gz";
    sha256 = "2db3f3a0d6ea4b59e1f094ace2c8cd536dffb87cdc39084c5afa1e6f7f37dd09";
  }
  {
    name = "OpenVDB";
    url = "https://github.com/AcademySoftwareFoundation/openvdb/archive/refs/tags/v11.0.0.zip";
    sha256 = "db7e1aacd0a634195574b2e6a43d268d063830628501fd0a94a99bf252d01fb6";
  }
  {
    name = "PNG";
    url = "https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.58.zip";
    sha256 = "ad8fc23d75a76f352989bbec9e905bdfe8f2d2e77b32e4f2070a4bb1849802ee";
  }
  {
    name = "Qhull";
    url = "https://github.com/qhull/qhull/archive/refs/tags/v8.1-alpha3.zip";
    sha256 = "7bd9b5ffae01e69c2ead52f9a9b688af6c65f9a1da05da0a170fa20d81404c06";
  }
  {
    name = "SDL";
    url = "https://github.com/libsdl-org/SDL/releases/download/release-2.32.4/SDL2-2.32.4.zip";
    sha256 = "030bd2768653bf11cefef06aaa99e61e850326871d283b81d324fb7242b6c702";
  }
  {
    name = "Sol2";
    url = "https://github.com/ThePhD/sol2/archive/refs/tags/v3.5.0.zip";
    sha256 = "b43e539415956960055f62a9d328fec3fd1ad4f272d6206631b9f022b0b12678";
  }
  {
    name = "TBB";
    url = "https://github.com/oneapi-src/oneTBB/archive/refs/tags/v2021.12.0.zip";
    sha256 = "fe6ca052b5bdd2c6e0616b360c9b0dcbcc46e01bbd0aa8fd0517c17fc58931db";
  }
  {
    name = "Tracy";
    url = "https://github.com/wolfpld/tracy/archive/refs/tags/v0.13.1.tar.gz";
    sha256 = "d4efc50ebcb0bfcfdbba148995aeb75044c0d80f5d91223aebfaa8fa9e563d2b";
  }
  {
    name = "Trumpeloeil";
    url = "https://github.com/rollbear/trompeloeil/archive/refs/tags/v49.zip";
    sha256 = "53f3339c6f3d48817c911e7a0894f91d3afb3bc1f2ee89a9b779a44c3f2d3a7c";
  }
  {
    name = "ZLIB";
    url = "https://github.com/madler/zlib/releases/download/v1.3.1/zlib131.zip";
    sha256 = "72af66d44fcc14c22013b46b814d5d2514673dda3d115e64b690c1ad636e7b17";
  }
  {
    name = "cpptrace";
    url = "https://github.com/jeremy-rifkin/cpptrace/archive/refs/tags/v1.0.4.zip";
    sha256 = "3fca735735cd74d646833f86112223f8aceb965055c8f96686a41d85948b50ba";
  }
  {
    name = "expected";
    url = "https://github.com/TartanLlama/expected/archive/refs/tags/v1.1.0.zip";
    sha256 = "4b2a347cf5450e99f7624247f7d78f86f3adb5e6acd33ce307094e9507615b78";
  }
  {
    name = "fmt";
    url = "https://github.com/fmtlib/fmt/releases/download/12.1.0/fmt-12.1.0.zip";
    sha256 = "695fd197fa5aff8fc67b5f2bbc110490a875cdf7a41686ac8512fb480fa8ada7";
  }
  {
    name = "heatshrink";
    url = "https://github.com/atomicobject/heatshrink/archive/refs/tags/v0.4.1.zip";
    sha256 = "2e2db2366bdf36cb450f0b3229467cbc6ea81a8c690723e4227b0b46f92584fe";
  }
  {
    name = "json";
    url = "https://github.com/nlohmann/json/archive/refs/tags/v3.12.0.zip";
    sha256 = "34660b5e9a407195d55e8da705ed26cc6d175ce5a6b1fb957e701fb4d5b04022";
  }
  {
    name = "libdeflate";
    url = "https://github.com/ebiggers/libdeflate/archive/refs/tags/v1.26.zip";
    sha256 = "cc64b9177e8c7eed2d3960a3dd9b0aa061ddc4c43c9067af1209e208e4a8144f";
  }
  {
    name = "libdwarf";
    url = "https://github.com/davea42/libdwarf-code/releases/download/v0.11.1/libdwarf-0.11.1.tar.xz";
    sha256 = "b5be211b1bd0c1ee41b871b543c73cbff5822f76994f6b160fc70d01d1b5a1bf";
  }
  {
    name = "magic_enum";
    url = "https://github.com/Neargye/magic_enum/archive/refs/tags/v0.9.7.zip";
    sha256 = "e293afdaf4d5918bc145903bccff06d28b3ed437f1ac8414ace9e8a769a9e470";
  }
  {
    name = "prusa_fdm_mixer";
    url = "https://github.com/prusa3d/prusa-fdm-mixer/archive/09d372aeccb4f7b9a0efbe59d99d70dba196814a.zip";
    sha256 = "795b3dec5fe64e59054f648d43e527c476a52bc38fe19cf3ae3be62f817de660";
  }
  {
    name = "pugixml";
    url = "https://github.com/zeux/pugixml/releases/download/v1.15/pugixml-1.15.zip";
    sha256 = "4e1aa9a5b5654b63b2ae5c4cd10b88ac295e91c86b1f563e5f8ce5a444b52311";
  }
  {
    name = "rangev3";
    url = "https://github.com/ericniebler/range-v3/archive/refs/tags/0.12.0.tar.gz";
    sha256 = "015adb2300a98edfceaf0725beec3337f542af4915cec4d0b89fa0886f4ba9cb";
  }
  {
    name = "ryml";
    url = "https://github.com/biojppm/rapidyaml/releases/download/v0.10.0/rapidyaml-0.10.0-src.tgz";
    sha256 = "54eb1050789809a26c780f80857b7668a5b3123405d6514a65d733e4292c690b";
  }
  {
    name = "spdlog";
    url = "https://github.com/gabime/spdlog/archive/refs/tags/v1.15.3.zip";
    sha256 = "b74274c32c8be5dba70b7006c1d41b7d3e5ff0dff8390c8b6390c1189424e094";
  }
  {
    name = "wxWidgets";
    url = "https://github.com/wxWidgets/wxWidgets/archive/49c6810948f40c457e3d0848b9111627b5b61de5.zip";
    sha256 = "5f5c34273ada47c50786749e7256efb3ca1281e5d430a9ca837b03a5aaab4a27";
  }
  {
    name = "yamlCpp";
    url = "https://github.com/jbeder/yaml-cpp/releases/download/yaml-cpp-0.9.0/yaml-cpp-yaml-cpp-0.9.0.tar.gz";
    sha256 = "298593d9c440fd9034b8b193d96318b76d49bc97c6ceadb7b0836edf0b6d7539";
  }
  {
    name = "yoga";
    url = "https://github.com/facebook/yoga/archive/refs/tags/v3.1.0.zip";
    sha256 = "8beed938026292f3a5d34b9b8dbe9e8b6c1e90c16292a37ff1f7240dbcabe5f2";
  }
  {
    name = "z3";
    url = "https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.15.1.zip";
    sha256 = "5072309889a8fe73381303949114391ae2c976b7df64886f4cbdae349dd39cae";
  }
  {
    name = "zstd";
    url = "https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-1.5.6.tar.gz";
    sha256 = "8c29e06cf42aacc1eafc4077ae2ec6c6fcb96a626157e0593d5e82a34fd403c1";
  }
]
